language: bash

services:
- docker

script:
- docker login --username=$ALI_USERNAME registry.cn-zhangjiakou.aliyuncs.com -p $ALI_PASSWORD
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- bash push-images.sh
